using DBPF_Compiler.FileTypes;
using DBPF_Compiler.FNV;

namespace DBPF_Compiler.DBPF
{
    public class DBPFPackerHelper
    {
        public string? ProjectFolderPath { get; set; }
        public string? ProjectName { get; set; }

        private LocalizationTable? _localizationTable;
        public LocalizationTable LocalizationTable
            => _localizationTable ??= new LocalizationTable();

        private Random? _random;

        internal void WriteHelperData(DatabasePackedFile dbpf)
        {
            if (_localizationTable == null)
                return;

            uint tableID;
            if (string.IsNullOrWhiteSpace(ProjectName))
            {
                _random ??= new Random();
                do
                {
                    tableID = (uint)_random.Next();
                } while (tableID <= 1000);
            }
            else
                tableID = FNVHash.Compute(ProjectName + "__autogenerated");

            dbpf.WriteSporeFile(_localizationTable,
                new(tableID, (uint)TypeIDs.locale, (uint)GroupIDs.locale));
        }
    }
}
